import { useCallback, useEffect, useMemo, useState } from 'react';
import { Calendar, ChevronLeft, ChevronRight, Clock3, MapPin, Search, Star, UserRound, Wrench } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { adminApi } from '../api/adminApi';
import { AdminCard, AdminDatePicker, ConfirmActionDialog, DetailDrawer, EmptyState, FilterBar, FormSection, Skeleton, StatusBadge } from '../components/AdminUI';
import { adminErrorMessage, adminServiceDescription, adminServiceName, adminStatusLabel, useAdminT } from '../adminI18n';
import type { AdminRequestDetail, AdminRequestListItem, Pagination } from '../types';
import { RequestTimeline } from './requests/RequestTimeline';
import { WorkerResponses } from './requests/WorkerResponses';

export default function RequestsModule() {
  const { t, lang } = useAdminT();
  const locale = lang === 'es' ? 'es-ES' : 'en-US';
  const money = (value: number | null | undefined) => Number(value || 0).toLocaleString(locale, { style: 'currency', currency: 'USD' });
  const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString(locale) : t('common.notAvailable');
  const [params, setParams] = useSearchParams();
  const [rows, setRows] = useState<AdminRequestListItem[]>([]);
  const [pagination, setPagination] = useState<Pagination>({ page: 1, limit: 25, total: 0, pages: 1 });
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [detail, setDetail] = useState<AdminRequestDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const [action, setAction] = useState<'cancel' | 'reassign' | 'resolve' | null>(null); const [reason, setReason] = useState(''); const [acting, setActing] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const query = new URLSearchParams(params); query.delete('request'); const payload = await adminApi.get<{ data?: AdminRequestListItem[]; requests?: AdminRequestListItem[]; pagination: Pagination }>(`${adminApi.endpoints.requestsHistory}?${query}`); setRows(payload.data || payload.requests || []); setPagination(payload.pagination || { page: 1, limit: 25, total: 0, pages: 1 }); } catch (reason) { setError(adminErrorMessage(reason, t('requests.loadError'), t)); } finally { setLoading(false); } }, [params, t]);
  const openDetail = useCallback(async (id: number) => { setDetailLoading(true); try { const payload = await adminApi.get<{ data: AdminRequestDetail }>(adminApi.endpoints.requestDetail(id)); setDetail(payload.data); } catch (reason) { setError(adminErrorMessage(reason, t('requests.detailError'), t)); } finally { setDetailLoading(false); } }, [t]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const id = Number(params.get('request')); if (id && detail?.id_request !== id) openDetail(id); }, [params, detail?.id_request, openDetail]);
  const updateFilter = (key: string, value: string) => setParams((current) => { const next = new URLSearchParams(current); if (value && value !== 'all') next.set(key, value); else next.delete(key); next.set('page', '1'); return next; });
  const submitAction = async () => { if (!detail || !action) return; setActing(true); try { await adminApi.post(adminApi.endpoints.requestActions(detail.id_request), { action, reason }); setAction(null); setReason(''); await Promise.all([load(), openDetail(detail.id_request)]); } catch (reason) { setError(adminErrorMessage(reason, t('requests.actionFailed'), t)); } finally { setActing(false); } };
  return <div className="admin-page-stack">
    <FilterBar><label className="admin-search-field"><Search size={17} /><input value={params.get('search') || ''} onChange={(e) => updateFilter('search', e.target.value)} placeholder={t('requests.search')} maxLength={120} /></label><select aria-label={t('common.status')} value={params.get('status') || 'all'} onChange={(e) => updateFilter('status', e.target.value)}><option value="all">{t('common.allStatuses')}</option>{['pending', 'payment_pending', 'paid', 'assigned', 'in_progress', 'awaiting_confirmation', 'done', 'cancelled'].map((value) => <option key={value} value={value}>{adminStatusLabel(value, lang)}</option>)}</select><select aria-label={t('requests.paymentStatus')} value={params.get('payment_status') || 'all'} onChange={(e) => updateFilter('payment_status', e.target.value)}><option value="all">{t('common.allPayments')}</option>{['pending', 'paid', 'released', 'refunded', 'failed', 'cancelled'].map((value) => <option key={value} value={value}>{adminStatusLabel(value, lang)}</option>)}</select><AdminDatePicker label={t('requests.fromDate')} value={params.get('date_from') || ''} placeholder={t('requests.fromDate')} onChange={(value) => updateFilter('date_from', value)} /><AdminDatePicker label={t('requests.toDate')} value={params.get('date_to') || ''} placeholder={t('requests.toDate')} onChange={(value) => updateFilter('date_to', value)} /></FilterBar>
    {error && <div className="admin-inline-error">{error}</div>}{loading ? <Skeleton rows={8} /> : rows.length === 0 ? <EmptyState title={t('requests.emptyTitle')} description={t('requests.emptyDescription')} /> : <AdminCard className="admin-request-history">
      <div className="admin-section-heading"><div><p className="admin-section-title">{t('requests.history')}</p><p className="admin-muted">{t('requests.historyNote')}</p></div><strong>{t('requests.requestCount', { count: pagination.total.toLocaleString(locale) })}</strong></div>
      <div className="admin-request-history-list">{rows.map((row) => <button key={row.id_request} type="button" onClick={() => setParams((current) => { const next = new URLSearchParams(current); next.set('request', String(row.id_request)); return next; })}>
        <span className="admin-request-avatar"><Wrench size={20} /></span>
        <span className="admin-request-main"><strong><span className="admin-request-number">#{row.id_request}</span> · {adminServiceName(row.service_name, lang)}</strong><small><MapPin size={12} />{row.location_text || t('requests.locationUnavailable')}</small></span>
        <span className="admin-request-meta"><small>{t('requests.client')}</small><strong>{row.client?.name || t('common.guest')}</strong></span>
        <span className="admin-request-meta"><small>{t('requests.professional')}</small><strong>{row.assigned_worker?.name || t('common.unassigned')}</strong></span>
        <span className="admin-request-meta"><small>{t('common.created')}</small><strong><Clock3 size={12} />{date(row.created_at)}</strong></span>
        <span className="admin-request-state"><StatusBadge status={row.status} /><StatusBadge status={row.payment_status} /></span>
        <span className="admin-request-price"><small>{t('requests.value')}</small><strong>{money(row.payment_amount ?? row.proposed_budget ?? row.budget)}</strong></span>
      </button>)}</div>
      <footer className="admin-pagination"><span>{t('common.records', { count: pagination.total.toLocaleString(locale) })}</span><div><button aria-label={t('common.previousPage')} disabled={pagination.page <= 1} onClick={() => updateFilter('page', String(pagination.page - 1))}><ChevronLeft size={16} /></button><span>{t('common.pageOf', { page: pagination.page, pages: pagination.pages })}</span><button aria-label={t('common.nextPage')} disabled={pagination.page >= pagination.pages} onClick={() => updateFilter('page', String(pagination.page + 1))}><ChevronRight size={16} /></button></div></footer>
    </AdminCard>}
    <DetailDrawer open={detailLoading || !!detail} title={detail ? t('requests.requestTitle', { id: detail.id_request }) : t('requests.loading')} subtitle={detail ? adminServiceName(detail.service_name, lang) : undefined} onClose={() => { setDetail(null); setParams((current) => { const next = new URLSearchParams(current); next.delete('request'); return next; }); }}>{detailLoading || !detail ? <Skeleton rows={7} /> : <div className="admin-detail-stack">
      <div className="admin-detail-hero"><div><StatusBadge status={detail.status} /><h3>{adminServiceName(detail.service_name, lang)}</h3><p>{adminServiceDescription(detail.description, lang)}</p></div><div><strong>{money(detail.final_budget || detail.payment?.amount || detail.budget)}</strong><span>{t('requests.currentValue')}</span></div></div>
      <div className="admin-detail-grid"><AdminCard><UserRound /><span>{t('requests.client')}</span><strong>{detail.client?.name || t('common.guest')}</strong><small>{detail.client?.email || t('common.noEmail')}<br />{detail.client?.phone || t('common.noPhone')}</small></AdminCard><AdminCard><Wrench /><span>{t('requests.professional')}</span><strong>{detail.assigned_worker?.name || t('common.unassigned')}</strong><small>{detail.assigned_worker?.email || t('common.noEmail')}<br />{detail.assigned_worker?.phone || t('common.noPhone')}</small></AdminCard><AdminCard><MapPin /><span>{t('requests.location')}</span><strong>{detail.location_text}</strong><small>{detail.latitude && detail.longitude ? `${detail.latitude}, ${detail.longitude}` : t('requests.coordinatesUnavailable')}</small></AdminCard><AdminCard><Calendar /><span>{t('requests.timeline')}</span><strong>{date(detail.created_at)}</strong><small>{t('requests.updated', { date: date(detail.updated_at) })}</small></AdminCard></div>
      <RequestTimeline request={detail} />
      <FormSection title={t('requests.financialBreakdown')}><div className="admin-kv"><span>{t('requests.initialBudget')}</span><strong>{money(detail.initial_budget)}</strong></div><div className="admin-kv"><span>{t('requests.counterOffer')}</span><strong>{money(detail.offer?.proposed_budget)}</strong></div><div className="admin-kv"><span>{t('requests.payment')}</span><strong>{money(detail.payment?.amount)}</strong></div><div className="admin-kv"><span>{t('requests.platformFee')}</span><strong>{money(detail.payment?.platform_fee)}</strong></div><div className="admin-kv"><span>{t('requests.professionalPayout')}</span><strong>{money(detail.payment?.worker_payout)}</strong></div><div className="admin-kv"><span>{t('requests.paymentStatus')}</span><StatusBadge status={detail.payment?.status || 'unpaid'} /></div></FormSection>
      <WorkerResponses responses={detail.worker_responses} />
      {detail.images.length > 0 && <FormSection title={t('requests.evidence', { count: detail.images.length })}><div className="admin-image-grid">{detail.images.map((item) => item.url && <a key={item.id_image} href={item.url} target="_blank" rel="noopener noreferrer"><img src={item.url} alt={t('requests.evidenceAlt', { id: item.id_image })} loading="lazy" /></a>)}</div></FormSection>}
      <FormSection title={t('requests.conversation', { count: detail.messages.length })} description={t('requests.readOnlyContext')}><div className="admin-message-list">{detail.messages.length === 0 ? <p className="admin-muted">{t('requests.noMessages')}</p> : detail.messages.map((message) => <div key={message.id_message} className={`admin-message admin-message--${message.sender_role}`}><strong>{message.sender_role === 'worker' ? t('requests.professional') : t('requests.client')}</strong><p>{message.message || t('requests.imageAttachment')}</p><small>{date(message.created_at)}</small></div>)}</div></FormSection>
      {detail.rating && <FormSection title={t('requests.customerRating')}><div className="admin-rating"><Star /><strong>{((detail.rating.punctuality + detail.rating.quality + detail.rating.price_fairness) / 3).toFixed(1)} / 5</strong><span>{detail.rating.comment || t('requests.noFeedback')}</span></div></FormSection>}
      <AdminCard><p className="admin-section-title">{t('requests.adminActions')}</p><p className="admin-muted">{t('requests.adminActionsNote')}</p><div className="admin-action-row">{!['done', 'cancelled'].includes(detail.status) && <><button className="admin-button admin-button--secondary" onClick={() => setAction('reassign')}>{t('requests.reassign')}</button><button className="admin-button admin-button--danger" onClick={() => setAction('cancel')}>{t('requests.cancelRequest')}</button></>}{['in_progress', 'awaiting_confirmation'].includes(detail.status) && <button className="admin-button" onClick={() => setAction('resolve')}>{t('requests.resolveComplete')}</button>}</div></AdminCard>
    </div>}</DetailDrawer>
    <ConfirmActionDialog open={!!action} title={t('requests.actionTitle', { action: action ? t(`requests.action.${action}`) : '', id: detail?.id_request || '' })} description={t('requests.actionDescription')} confirmLabel={t('requests.confirmAction')} reason={reason} onReasonChange={setReason} onCancel={() => { setAction(null); setReason(''); }} onConfirm={submitAction} busy={acting} />
  </div>;
}
