import { useCallback, useEffect, useMemo, useState } from 'react';
import { Calendar, ChevronLeft, ChevronRight, Clock3, MapPin, Search, Star, UserRound, Wrench } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { adminApi } from '../api/adminApi';
import { AdminCard, ConfirmActionDialog, DetailDrawer, EmptyState, FilterBar, FormSection, Skeleton, StatusBadge } from '../components/AdminUI';
import type { AdminRequestDetail, AdminRequestListItem, Pagination } from '../types';
import { RequestTimeline } from './requests/RequestTimeline';
import { WorkerResponses } from './requests/WorkerResponses';

const money = (value: number | null | undefined) => Number(value || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : 'Not available';

export default function RequestsModule() {
  const [params, setParams] = useSearchParams();
  const [rows, setRows] = useState<AdminRequestListItem[]>([]);
  const [pagination, setPagination] = useState<Pagination>({ page: 1, limit: 25, total: 0, pages: 1 });
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [detail, setDetail] = useState<AdminRequestDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const [action, setAction] = useState<'cancel' | 'reassign' | 'resolve' | null>(null); const [reason, setReason] = useState(''); const [acting, setActing] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const query = new URLSearchParams(params); query.delete('request'); const payload = await adminApi.get<{ data?: AdminRequestListItem[]; requests?: AdminRequestListItem[]; pagination: Pagination }>(`${adminApi.endpoints.requestsHistory}?${query}`); setRows(payload.data || payload.requests || []); setPagination(payload.pagination || { page: 1, limit: 25, total: 0, pages: 1 }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load requests.'); } finally { setLoading(false); } }, [params]);
  const openDetail = useCallback(async (id: number) => { setDetailLoading(true); try { const payload = await adminApi.get<{ data: AdminRequestDetail }>(adminApi.endpoints.requestDetail(id)); setDetail(payload.data); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load request detail.'); } finally { setDetailLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const id = Number(params.get('request')); if (id && detail?.id_request !== id) openDetail(id); }, [params, detail?.id_request, openDetail]);
  const updateFilter = (key: string, value: string) => setParams((current) => { const next = new URLSearchParams(current); if (value && value !== 'all') next.set(key, value); else next.delete(key); next.set('page', '1'); return next; });
  const submitAction = async () => { if (!detail || !action) return; setActing(true); try { await adminApi.post(adminApi.endpoints.requestActions(detail.id_request), { action, reason }); setAction(null); setReason(''); await Promise.all([load(), openDetail(detail.id_request)]); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Action failed.'); } finally { setActing(false); } };
  return <div className="admin-page-stack">
    <FilterBar><label className="admin-search-field"><Search size={17} /><input value={params.get('search') || ''} onChange={(e) => updateFilter('search', e.target.value)} placeholder="Search ID, client, pro or location" /></label><select aria-label="Request status" value={params.get('status') || 'all'} onChange={(e) => updateFilter('status', e.target.value)}><option value="all">All statuses</option>{['pending', 'payment_pending', 'paid', 'assigned', 'in_progress', 'awaiting_confirmation', 'done', 'cancelled'].map((value) => <option key={value} value={value}>{value.replace(/_/g, ' ')}</option>)}</select><select aria-label="Payment status" value={params.get('payment_status') || 'all'} onChange={(e) => updateFilter('payment_status', e.target.value)}><option value="all">All payments</option>{['pending', 'paid', 'released', 'refunded', 'failed', 'cancelled'].map((value) => <option key={value} value={value}>{value}</option>)}</select><input aria-label="From date" type="date" value={params.get('date_from') || ''} onChange={(e) => updateFilter('date_from', e.target.value)} /><input aria-label="To date" type="date" value={params.get('date_to') || ''} onChange={(e) => updateFilter('date_to', e.target.value)} /></FilterBar>
    {error && <div className="admin-inline-error">{error}</div>}{loading ? <Skeleton rows={8} /> : rows.length === 0 ? <EmptyState title="No requests found" description="Change filters or wait for new service requests." /> : <AdminCard className="admin-request-history">
      <div className="admin-section-heading"><div><p className="admin-section-title">Request history</p><p className="admin-muted">Live operational record with client, assignment and payment state</p></div><strong>{pagination.total.toLocaleString()} requests</strong></div>
      <div className="admin-request-history-list">{rows.map((row) => <button key={row.id_request} type="button" onClick={() => setParams((current) => { const next = new URLSearchParams(current); next.set('request', String(row.id_request)); return next; })}>
        <span className="admin-request-avatar"><Wrench size={20} /></span>
        <span className="admin-request-main"><strong><span className="admin-request-number">#{row.id_request}</span> · {row.service_name}</strong><small><MapPin size={12} />{row.location_text || 'Location unavailable'}</small></span>
        <span className="admin-request-meta"><small>Client</small><strong>{row.client?.name || 'Guest'}</strong></span>
        <span className="admin-request-meta"><small>Professional</small><strong>{row.assigned_worker?.name || 'Unassigned'}</strong></span>
        <span className="admin-request-meta"><small>Created</small><strong><Clock3 size={12} />{date(row.created_at)}</strong></span>
        <span className="admin-request-state"><StatusBadge status={row.status} /><StatusBadge status={row.payment_status} /></span>
        <span className="admin-request-price"><small>Value</small><strong>{money(row.payment_amount ?? row.proposed_budget ?? row.budget)}</strong></span>
      </button>)}</div>
      <footer className="admin-pagination"><span>{pagination.total.toLocaleString()} records</span><div><button aria-label="Previous page" disabled={pagination.page <= 1} onClick={() => updateFilter('page', String(pagination.page - 1))}><ChevronLeft size={16} /></button><span>Page {pagination.page} of {pagination.pages}</span><button aria-label="Next page" disabled={pagination.page >= pagination.pages} onClick={() => updateFilter('page', String(pagination.page + 1))}><ChevronRight size={16} /></button></div></footer>
    </AdminCard>}
    <DetailDrawer open={detailLoading || !!detail} title={detail ? `Request #${detail.id_request}` : 'Loading request'} subtitle={detail?.service_name} onClose={() => { setDetail(null); setParams((current) => { const next = new URLSearchParams(current); next.delete('request'); return next; }); }}>{detailLoading || !detail ? <Skeleton rows={7} /> : <div className="admin-detail-stack">
      <div className="admin-detail-hero"><div><StatusBadge status={detail.status} /><h3>{detail.service_name}</h3><p>{detail.description}</p></div><div><strong>{money(detail.final_budget || detail.payment?.amount || detail.budget)}</strong><span>Current value</span></div></div>
      <div className="admin-detail-grid"><AdminCard><UserRound /><span>Client</span><strong>{detail.client?.name || 'Guest'}</strong><small>{detail.client?.email || 'No email'}<br />{detail.client?.phone || 'No phone'}</small></AdminCard><AdminCard><Wrench /><span>Professional</span><strong>{detail.assigned_worker?.name || 'Unassigned'}</strong><small>{detail.assigned_worker?.email || 'No email'}<br />{detail.assigned_worker?.phone || 'No phone'}</small></AdminCard><AdminCard><MapPin /><span>Location</span><strong>{detail.location_text}</strong><small>{detail.latitude && detail.longitude ? `${detail.latitude}, ${detail.longitude}` : 'Coordinates unavailable'}</small></AdminCard><AdminCard><Calendar /><span>Timeline</span><strong>{date(detail.created_at)}</strong><small>Updated {date(detail.updated_at)}</small></AdminCard></div>
      <RequestTimeline request={detail} />
      <FormSection title="Financial breakdown"><div className="admin-kv"><span>Initial budget</span><strong>{money(detail.initial_budget)}</strong></div><div className="admin-kv"><span>Counter offer</span><strong>{money(detail.offer?.proposed_budget)}</strong></div><div className="admin-kv"><span>Payment</span><strong>{money(detail.payment?.amount)}</strong></div><div className="admin-kv"><span>Platform fee</span><strong>{money(detail.payment?.platform_fee)}</strong></div><div className="admin-kv"><span>Professional payout</span><strong>{money(detail.payment?.worker_payout)}</strong></div><div className="admin-kv"><span>Payment status</span><StatusBadge status={detail.payment?.status || 'unpaid'} /></div></FormSection>
      <WorkerResponses responses={detail.worker_responses} />
      {detail.images.length > 0 && <FormSection title={`Evidence (${detail.images.length})`}><div className="admin-image-grid">{detail.images.map((item) => item.url && <a key={item.id_image} href={item.url} target="_blank" rel="noopener noreferrer"><img src={item.url} alt={`Request evidence ${item.id_image}`} loading="lazy" /></a>)}</div></FormSection>}
      <FormSection title={`Conversation (${detail.messages.length})`} description="Read-only operational context"><div className="admin-message-list">{detail.messages.length === 0 ? <p className="admin-muted">No messages.</p> : detail.messages.map((message) => <div key={message.id_message} className={`admin-message admin-message--${message.sender_role}`}><strong>{message.sender_role === 'worker' ? 'Professional' : 'Client'}</strong><p>{message.message || 'Image attachment'}</p><small>{date(message.created_at)}</small></div>)}</div></FormSection>
      {detail.rating && <FormSection title="Customer rating"><div className="admin-rating"><Star /><strong>{((detail.rating.punctuality + detail.rating.quality + detail.rating.price_fairness) / 3).toFixed(1)} / 5</strong><span>{detail.rating.comment || 'No written feedback'}</span></div></FormSection>}
      <AdminCard><p className="admin-section-title">Administrative actions</p><p className="admin-muted">Every action requires reason and creates audit entry.</p><div className="admin-action-row">{!['done', 'cancelled'].includes(detail.status) && <><button className="admin-button admin-button--secondary" onClick={() => setAction('reassign')}>Reassign</button><button className="admin-button admin-button--danger" onClick={() => setAction('cancel')}>Cancel request</button></>}{['in_progress', 'awaiting_confirmation'].includes(detail.status) && <button className="admin-button" onClick={() => setAction('resolve')}>Resolve as complete</button>}</div></AdminCard>
    </div>}</DetailDrawer>
    <ConfirmActionDialog open={!!action} title={`${action ? action[0].toUpperCase() + action.slice(1) : ''} request #${detail?.id_request || ''}`} description="This changes live request state and will be recorded in admin activity." confirmLabel="Confirm action" reason={reason} onReasonChange={setReason} onCancel={() => { setAction(null); setReason(''); }} onConfirm={submitAction} busy={acting} />
  </div>;
}
