import { useCallback, useEffect, useState } from 'react';
import { DollarSign, Plus, Trash2 } from 'lucide-react';
import { adminApi } from '../api/adminApi';
import { AdminCard, DataTable, EmptyState, FormSection, Skeleton, StatusBadge } from '../components/AdminUI';

type Service = { id_service:number; name:string; description:string|null; icon:string|null; is_active:number; request_count:number; completed_count:number; cancelled_count:number; paid_volume:number; last_request_at:string|null };

export default function ServicesModule() {
  const [rows,setRows]=useState<Service[]>([]); const [loading,setLoading]=useState(true); const [editing,setEditing]=useState<Service|null>(null);
  const [form,setForm]=useState({name:'',description:'',icon:''}); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const payload=await adminApi.get<{services:Service[]}>(adminApi.endpoints.services);setRows(payload.services||[])}catch(reason){setError(reason instanceof Error?reason.message:'Could not load services.')}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const reset=()=>{setEditing(null);setForm({name:'',description:'',icon:''})};
  const save=async()=>{if(!form.name.trim())return;setSaving(true);try{const body={name:form.name.trim(),description:form.description.trim(),icon:form.icon.trim()};if(editing)await adminApi.put(`${adminApi.endpoints.services}/${editing.id_service}`,body);else await adminApi.post(adminApi.endpoints.services,body);reset();await load()}catch(reason){setError(reason instanceof Error?reason.message:'Could not save service.')}finally{setSaving(false)}};
  const toggle=async(service:Service)=>{try{await adminApi.put(`${adminApi.endpoints.services}/${service.id_service}`,{is_active:!service.is_active});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Could not update service.')}};
  const remove=async(service:Service)=>{if(service.request_count>0){setError('Service has request history. Deactivate it instead of deleting it.');return}if(!window.confirm(`Delete service "${service.name}"?`))return;try{await adminApi.delete(`${adminApi.endpoints.services}/${service.id_service}`);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Could not delete service.')}};
  const edit=(service:Service)=>{setEditing(service);setForm({name:service.name,description:service.description||'',icon:service.icon||''});window.scrollTo({top:0,behavior:'smooth'})};
  return <div className="admin-page-stack"><AdminCard><div className="admin-section-heading"><div><p className="admin-section-title">{editing?'Edit service':'Add service'}</p><p className="admin-muted">Operational category. Historical services should be deactivated, not deleted.</p></div><Plus/></div><FormSection title="Essential information"><label className="admin-field"><span>Name</span><input value={form.name} maxLength={100} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label className="admin-field admin-field--wide"><span>Description</span><textarea value={form.description} maxLength={500} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><details className="admin-advanced admin-field--wide"><summary>Advanced presentation</summary><label className="admin-field"><span>Icon value</span><input value={form.icon} maxLength={100} onChange={(e)=>setForm({...form,icon:e.target.value})}/></label></details></FormSection>{error&&<div className="admin-inline-error">{error}</div>}<div className="admin-action-row">{editing&&<button className="admin-button admin-button--secondary" onClick={reset}>Cancel</button>}<button className="admin-button" disabled={saving} onClick={save}>{saving?'Saving...':editing?'Save changes':'Create service'}</button></div></AdminCard>
    {loading?<Skeleton rows={6}/>:rows.length===0?<EmptyState title="No services" description="Create first service category."/>:<DataTable rows={rows} rowKey={(service)=>service.id_service} onRowClick={edit} columns={[{key:'name',label:'Service',render:(service)=><div className="admin-primary-cell"><strong>{service.name}</strong><span>{service.description||'No description'}</span></div>},{key:'requests',label:'Requests',render:(service)=><strong>{service.request_count}</strong>},{key:'completed',label:'Completed',render:(service)=>`${service.completed_count} (${service.request_count?Math.round(service.completed_count/service.request_count*100):0}%)`},{key:'volume',label:'Paid volume',render:(service)=><span className="admin-rating-inline"><DollarSign size={14}/>{service.paid_volume.toFixed(2)}</span>},{key:'status',label:'Status',render:(service)=><StatusBadge status={service.is_active?'active':'inactive'}/>},{key:'actions',label:'Actions',render:(service)=><div className="admin-action-row"><button className="admin-button admin-button--secondary admin-button--small" onClick={(event)=>{event.stopPropagation();toggle(service)}}>{service.is_active?'Deactivate':'Activate'}</button><button className="admin-button admin-button--danger admin-button--small" disabled={service.request_count>0} onClick={(event)=>{event.stopPropagation();remove(service)}}><Trash2 size={13}/></button></div>}]}/>}</div>;
}
