export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export const API_ENDPOINTS = {
  auth: {
    login: `${API_URL}/api/auth/login`,
    registerUser: `${API_URL}/api/auth/register-user`,
    registerWorker: `${API_URL}/api/auth/register/worker`,
    verifyWorkerEmail: `${API_URL}/api/auth/verify-worker-email`,
    resendOtp: `${API_URL}/api/auth/resend-otp`,
    forgotPassword: `${API_URL}/api/auth/forgot-password`,
    verifyResetToken: `${API_URL}/api/auth/verify-reset-token`,
    resetPassword: `${API_URL}/api/auth/reset-password`,
    updateProfile: `${API_URL}/api/auth/profile`,
    uploadProfileImage: `${API_URL}/api/auth/profile-image`,
    removeProfileImage: `${API_URL}/api/auth/profile-image`,
  },
  services: {
    getActive: `${API_URL}/api/services`,
    cards: `${API_URL}/api/services/cards`,
    nearbyWorkers: `${API_URL}/api/services/nearby-workers`,
    createRequest: `${API_URL}/api/services/requests`,
    myRequests: `${API_URL}/api/services/my-requests`,
    cancelRequest: (idRequest: number) => `${API_URL}/api/services/requests/${idRequest}/cancel`,
    acceptCounter: (idRequest: number) => `${API_URL}/api/services/requests/${idRequest}/counter/accept`,
    declineCounter: (idRequest: number) => `${API_URL}/api/services/requests/${idRequest}/counter/decline`,
    requestChat: (idRequest: number) => `${API_URL}/api/services/requests/${idRequest}/chat`,
    requestRating: (idRequest: number) => `${API_URL}/api/services/requests/${idRequest}/rating`,
  },
  admin: {
    services: `${API_URL}/api/admin/services`,
    serviceCards: `${API_URL}/api/admin/service-cards`,
    uploadImageAsset: `${API_URL}/api/admin/hero-slides/image-upload`,
    pendingWorkers: `${API_URL}/api/admin/pending-workers`,
    approveWorker: (id: number) => `${API_URL}/api/admin/workers/${id}/approve`,
    rejectWorker: (id: number) => `${API_URL}/api/admin/workers/${id}/reject`,
    users: `${API_URL}/api/admin/users`,
    updateUserRole: (id: number) => `${API_URL}/api/admin/users/${id}/role`,
    updateUserStatus: (id: number) => `${API_URL}/api/admin/users/${id}/status`,
    stats: `${API_URL}/api/admin/stats`,
    requestsHistory: `${API_URL}/api/admin/requests-history`,
    activity: `${API_URL}/api/admin/activity`,
  },
  worker: {
    me: `${API_URL}/api/worker/me`,
    requests: `${API_URL}/api/worker/requests`,
    acceptRequest: (idRequest: number) => `${API_URL}/api/worker/requests/${idRequest}/accept`,
    rejectRequest: (idRequest: number) => `${API_URL}/api/worker/requests/${idRequest}/reject`,
    counterOffer: (idRequest: number) => `${API_URL}/api/worker/requests/${idRequest}/counter-offer`,
    presence: `${API_URL}/api/worker/presence`,
  },
};
