import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER || '',
    pass: process.env.EMAIL_PASS || '',
  },
});

const escapeHtml = (value: unknown) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const formatMoney = (value: number, currencyCode = 'USD') =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: String(currencyCode || 'USD').toUpperCase(),
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Number(value || 0));

const formatDateTime = (date: Date | string) =>
  new Date(date).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  });

const renderEmailShell = (input: {
  eyebrow: string;
  title: string;
  subtitle: string;
  accentStart: string;
  accentEnd: string;
  bodyHtml: string;
}) => `
  <div style="margin: 0; background: #f3f7fb; padding: 24px 12px; font-family: Arial, Helvetica, sans-serif;">
    <div style="max-width: 720px; margin: 0 auto; overflow: hidden; border-radius: 24px; border: 1px solid #dbe5f0; background: #ffffff; box-shadow: 0 24px 60px rgba(15, 23, 42, 0.12);">
      <div style="padding: 28px 28px 22px; background: linear-gradient(135deg, ${input.accentStart}, ${input.accentEnd}); color: #ffffff;">
        <div style="display: inline-block; margin-bottom: 14px; border-radius: 999px; background: rgba(255,255,255,0.16); padding: 8px 14px; font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase;">
          ${escapeHtml(input.eyebrow)}
        </div>
        <div style="font-size: 34px; font-weight: 800; letter-spacing: -0.02em;">Fixlife</div>
        <h1 style="margin: 14px 0 0; font-size: 28px; line-height: 1.2;">${escapeHtml(input.title)}</h1>
        <p style="margin: 10px 0 0; max-width: 520px; font-size: 15px; line-height: 1.6; opacity: 0.95;">${escapeHtml(input.subtitle)}</p>
      </div>
      <div style="padding: 28px; color: #0f172a;">
        ${input.bodyHtml}
      </div>
      <div style="padding: 20px 28px 28px; border-top: 1px solid #e5edf6; color: #64748b; font-size: 12px; line-height: 1.6;">
        This message was generated by Fixlife Billing. If you need help with this payment, reply to this email or contact support from your dashboard.
      </div>
    </div>
  </div>
`;

export const sendVerificationEmail = async (to: string, otp: string, name: string) => {
  const mailOptions = {
    from: `"Fixlife Support" <${process.env.EMAIL_USER || 'no-reply@fixlife.local'}>`,
    to,
    subject: 'Your Fixlife Verification Code',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #ff6b00; padding: 20px; text-align: center;">
          <h2 style="color: #ffffff; margin: 0;">Welcome to Fixlife Pros!</h2>
        </div>
        <div style="padding: 20px; color: #333333;">
          <p>Hi ${name},</p>
          <p>Thank you for joining Fixlife as a Pro. Please use the verification code below to complete your registration:</p>
          <div style="margin: 30px 0; text-align: center;">
            <span style="font-size: 32px; font-weight: bold; letter-spacing: 5px; color: #ff6b00; background-color: #fff4e6; padding: 15px 25px; border-radius: 8px;">${otp}</span>
          </div>
          <p style="font-size: 14px; color: #666666;">This code is valid for 15 minutes.</p>
          <p>If you didn't request this, please ignore this email.</p>
          <br>
          <p>Best regards,<br>The Fixlife Team</p>
        </div>
      </div>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Verification email sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending verification email:', error);
    return false;
  }
};

export const sendEmailChangeToken = async (to: string, otp: string, name: string) => {
  const mailOptions = {
    from: `"Fixlife Support" <${process.env.EMAIL_USER || 'no-reply@fixlife.local'}>`,
    to,
    subject: 'Fixlife - Verify Your New Email',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 10px; overflow: hidden;">
        <div style="background-color: #ff6b00; padding: 20px; text-align: center;">
          <h2 style="color: #ffffff; margin: 0; font-size: 30px;">Fixlife</h2>
        </div>
        <div style="padding: 24px; color: #333333; background: #ffffff;">
          <p>Hi ${name},</p>
          <p>We received a request to change your email in Fixlife. Use this code to verify your new email address:</p>
          <div style="margin: 28px 0; text-align: center;">
            <span style="font-size: 34px; font-weight: bold; letter-spacing: 7px; color: #ff6b00; background-color: #fff4e6; padding: 16px 26px; border-radius: 10px;">${otp}</span>
          </div>
          <p style="font-size: 14px; color: #666666;">This code is valid for 15 minutes.</p>
          <p>If you didn't request this change, ignore this email and secure your account.</p>
          <br>
          <p>Best regards,<br>The Fixlife Team</p>
        </div>
      </div>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Email change token sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending email change token:', error);
    return false;
  }
};

export const sendProfileChangeNotice = async (
  to: string,
  name: string,
  changes: string[]
) => {
  const changeItems = changes.map((change) => `<li>${change}</li>`).join('');
  const mailOptions = {
    from: `"Fixlife Security" <${process.env.EMAIL_USER || 'no-reply@fixlife.local'}>`,
    to,
    subject: 'Fixlife Account Changes Detected',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #111827; padding: 20px; text-align: center;">
          <h2 style="color: #ffffff; margin: 0;">Account Update Notification</h2>
        </div>
        <div style="padding: 20px; color: #111827;">
          <p>Hi ${name},</p>
          <p>These changes were made to your Fixlife account:</p>
          <ul>${changeItems}</ul>
          <p style="font-size: 14px; color: #4b5563;">If this wasn't you, reset your password immediately.</p>
          <p>Fixlife Team</p>
        </div>
      </div>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Profile change notice sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending profile change notice:', error);
    return false;
  }
};

export const sendPasswordResetEmail = async (to: string, otp: string, name: string) => {
  const mailOptions = {
    from: `"Fixlife Support" <${process.env.EMAIL_USER || 'no-reply@fixlife.local'}>`,
    to,
    subject: 'Reset Your Fixlife Password',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #0090FF; padding: 20px; text-align: center;">
          <h2 style="color: #ffffff; margin: 0;">Password Reset Request</h2>
        </div>
        <div style="padding: 20px; color: #333333;">
          <p>Hi ${name},</p>
          <p>We received a request to reset your Fixlife password. Use the verification code below to continue:</p>
          <div style="margin: 30px 0; text-align: center;">
            <span style="font-size: 32px; font-weight: bold; letter-spacing: 5px; color: #0090FF; background-color: #e6f4ff; padding: 15px 25px; border-radius: 8px;">${otp}</span>
          </div>
          <p style="font-size: 14px; color: #666666;">This code is valid for 15 minutes.</p>
          <p>If you didn't request this password reset, please ignore this email and your password will remain unchanged.</p>
          <br>
          <p>Best regards,<br>The Fixlife Team</p>
        </div>
      </div>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Password reset email sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending password reset email:', error);
    return false;
  }
};

type PaymentInvoiceInput = {
  to: string;
  customerName: string;
  requestId: number;
  serviceName: string;
  locationText?: string | null;
  urgencyLevel?: string | null;
  amount: number;
  platformFee: number;
  workerPayout: number;
  checkoutReference: string;
  invoiceNumber: string;
  provider: string;
  currencyCode?: string | null;
  commissionRatePercent?: number | null;
  policyLabel?: string | null;
  promoCode?: string | null;
  paidAt: Date;
};

export const sendPaymentInvoiceEmail = async (input: PaymentInvoiceInput) => {
  const subtotal = Number(Math.max(input.amount - input.platformFee, 0).toFixed(2));
  const currencyCode = String(input.currencyCode || 'USD').toUpperCase();
  const urgencyLabel = String(input.urgencyLevel || 'standard')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
  const policyLine = input.policyLabel ? escapeHtml(input.policyLabel) : 'Default commission policy';
  const promoLine = input.promoCode ? escapeHtml(String(input.promoCode).toUpperCase()) : null;
  const bodyHtml = `
    <p style="margin: 0 0 18px; font-size: 15px; line-height: 1.7;">Hi ${escapeHtml(input.customerName)}, your payment was successfully secured. Here is your Fixlife electronic invoice with the full breakdown for this service.</p>

    <div style="margin-bottom: 20px; display: grid; gap: 14px;">
      <div style="border-radius: 20px; border: 1px solid #dbe5f0; background: linear-gradient(180deg, #f8fbff, #ffffff); padding: 20px;">
        <div style="display: flex; justify-content: space-between; gap: 12px; flex-wrap: wrap;">
          <div>
            <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #2563eb;">Invoice</div>
            <div style="margin-top: 8px; font-size: 24px; font-weight: 800; color: #0f172a;">${escapeHtml(input.invoiceNumber)}</div>
            <div style="margin-top: 8px; font-size: 13px; color: #475569;">Paid on ${escapeHtml(formatDateTime(input.paidAt))}</div>
          </div>
          <div style="min-width: 210px; border-radius: 16px; background: #0f172a; padding: 16px; color: #ffffff;">
            <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; opacity: 0.78;">Total paid</div>
            <div style="margin-top: 8px; font-size: 30px; font-weight: 800;">${escapeHtml(formatMoney(input.amount, currencyCode))}</div>
            <div style="margin-top: 8px; font-size: 13px; opacity: 0.82;">Method: ${escapeHtml(String(input.provider || 'paypal').toUpperCase())}</div>
          </div>
        </div>
      </div>

      <div style="display: grid; gap: 14px; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));">
        <div style="border-radius: 18px; border: 1px solid #e2e8f0; background: #ffffff; padding: 18px;">
          <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #64748b;">Service</div>
          <div style="margin-top: 10px; font-size: 20px; font-weight: 800; color: #0f172a;">${escapeHtml(input.serviceName)}</div>
          <div style="margin-top: 8px; font-size: 13px; line-height: 1.6; color: #475569;">
            <div>Request #${escapeHtml(input.requestId)}</div>
            <div>Urgency: ${escapeHtml(urgencyLabel)}</div>
            ${input.locationText ? `<div>${escapeHtml(input.locationText)}</div>` : ''}
          </div>
        </div>
        <div style="border-radius: 18px; border: 1px solid #e2e8f0; background: #ffffff; padding: 18px;">
          <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #64748b;">Payment reference</div>
          <div style="margin-top: 10px; font-size: 20px; font-weight: 800; color: #0f172a;">${escapeHtml(input.checkoutReference)}</div>
          <div style="margin-top: 8px; font-size: 13px; line-height: 1.6; color: #475569;">
            <div>${escapeHtml(policyLine)}</div>
            ${promoLine ? `<div>Promo applied: ${promoLine}</div>` : ''}
            ${
              input.commissionRatePercent != null
                ? `<div>Platform fee: ${escapeHtml(Number(input.commissionRatePercent).toFixed(2))}%</div>`
                : ''
            }
          </div>
        </div>
      </div>

      <div style="border-radius: 20px; border: 1px solid #e2e8f0; background: #ffffff; padding: 18px 20px;">
        <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #64748b;">Financial breakdown</div>
        <table style="width: 100%; border-collapse: collapse; margin-top: 14px;">
          <tr>
            <td style="padding: 12px 0; border-bottom: 1px solid #e5edf6; color: #334155;">Service subtotal</td>
            <td style="padding: 12px 0; border-bottom: 1px solid #e5edf6; text-align: right; font-weight: 700; color: #0f172a;">${escapeHtml(formatMoney(subtotal, currencyCode))}</td>
          </tr>
          <tr>
            <td style="padding: 12px 0; border-bottom: 1px solid #e5edf6; color: #334155;">Fixlife fee</td>
            <td style="padding: 12px 0; border-bottom: 1px solid #e5edf6; text-align: right; font-weight: 700; color: #0f172a;">${escapeHtml(formatMoney(input.platformFee, currencyCode))}</td>
          </tr>
          <tr>
            <td style="padding: 12px 0; border-bottom: 1px solid #e5edf6; color: #334155;">Net worker payout</td>
            <td style="padding: 12px 0; border-bottom: 1px solid #e5edf6; text-align: right; font-weight: 700; color: #0f172a;">${escapeHtml(formatMoney(input.workerPayout, currencyCode))}</td>
          </tr>
          <tr>
            <td style="padding: 14px 0 0; color: #0f172a; font-size: 15px; font-weight: 800;">Total paid</td>
            <td style="padding: 14px 0 0; text-align: right; color: #0f172a; font-size: 20px; font-weight: 800;">${escapeHtml(formatMoney(input.amount, currencyCode))}</td>
          </tr>
        </table>
      </div>
    </div>

    <p style="margin: 0; font-size: 13px; line-height: 1.7; color: #475569;">Keep this email as your payment receipt. Your pro will see the secured funds in their dashboard, and Fixlife will preserve this breakdown even if your commission rules change later.</p>
  `;

  const mailOptions = {
    from: `"Fixlife Billing" <${process.env.EMAIL_USER || 'no-reply@fixlife.local'}>`,
    to: input.to,
    subject: `Fixlife Electronic Invoice - ${input.invoiceNumber}`,
    html: renderEmailShell({
      eyebrow: 'Billing',
      title: 'Electronic invoice',
      subtitle: 'A clean, printable receipt for your Fixlife payment, with the exact fee and payout breakdown used at checkout.',
      accentStart: '#003087',
      accentEnd: '#0070ba',
      bodyHtml,
    }),
    text: `Fixlife invoice ${input.invoiceNumber}
Request #${input.requestId}
Service: ${input.serviceName}
Reference: ${input.checkoutReference}
Paid: ${formatDateTime(input.paidAt)}
Total: ${formatMoney(input.amount, currencyCode)}
Fixlife fee: ${formatMoney(input.platformFee, currencyCode)}
Worker payout: ${formatMoney(input.workerPayout, currencyCode)}`,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Payment invoice email sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending payment invoice email:', error);
    return false;
  }
};

type WorkerPaymentNoticeInput = {
  to: string;
  workerName: string;
  requestId: number;
  serviceName: string;
  amount: number;
  checkoutReference: string;
};

export const sendWorkerPaymentSecuredEmail = async (input: WorkerPaymentNoticeInput) => {
  const bodyHtml = `
    <p style="margin: 0 0 18px; font-size: 15px; line-height: 1.7;">Hi ${escapeHtml(input.workerName)}, the client payment for this service is already secured. You can continue the job knowing the funds are locked in.</p>
    <div style="border-radius: 20px; border: 1px solid #d7f0e4; background: linear-gradient(180deg, #f0fdf4, #ffffff); padding: 20px;">
      <div style="display: grid; gap: 14px; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));">
        <div>
          <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #059669;">Request</div>
          <div style="margin-top: 8px; font-size: 22px; font-weight: 800; color: #0f172a;">#${escapeHtml(input.requestId)}</div>
          <div style="margin-top: 8px; font-size: 14px; color: #475569;">${escapeHtml(input.serviceName)}</div>
        </div>
        <div>
          <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #059669;">Secured amount</div>
          <div style="margin-top: 8px; font-size: 22px; font-weight: 800; color: #0f172a;">${escapeHtml(formatMoney(input.amount))}</div>
          <div style="margin-top: 8px; font-size: 14px; color: #475569;">Reference ${escapeHtml(input.checkoutReference)}</div>
        </div>
      </div>
    </div>
    <p style="margin: 18px 0 0; font-size: 13px; line-height: 1.7; color: #475569;">When the client confirms completion, this payout will move into the scheduled settlement cycle in your professional dashboard.</p>
  `;

  const mailOptions = {
    from: `"Fixlife Payments" <${process.env.EMAIL_USER || 'no-reply@fixlife.local'}>`,
    to: input.to,
    subject: `Payment confirmed for your service #${input.requestId}`,
    html: renderEmailShell({
      eyebrow: 'Payments',
      title: 'Client payment secured',
      subtitle: 'The job is now backed by secured funds, so you can move forward with confidence.',
      accentStart: '#059669',
      accentEnd: '#0f766e',
      bodyHtml,
    }),
    text: `Payment secured for request #${input.requestId}
Service: ${input.serviceName}
Secured amount: ${formatMoney(input.amount)}
Reference: ${input.checkoutReference}`,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Worker payment secured email sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending worker payment secured email:', error);
    return false;
  }
};

type WorkerPayoutPaidEmailInput = {
  to: string;
  workerName: string;
  payoutType: 'base' | 'bonus';
  amount: number;
  scheduledFor?: string | null;
  paidAt?: Date | string | null;
  requestId?: number | null;
  serviceName?: string | null;
  cycleKey?: string | null;
  bonusType?: string | null;
};

export const sendWorkerPayoutPaidEmail = async (input: WorkerPayoutPaidEmailInput) => {
  const isBonus = input.payoutType === 'bonus';
  const payoutTitle = isBonus ? 'Bonus payout released' : 'Worker payout released';
  const subtitle = isBonus
    ? 'Your performance-based payout has been marked as paid and is ready for your records.'
    : 'Your base payout from a completed Fixlife service has been marked as paid.';
  const bodyHtml = `
    <p style="margin: 0 0 18px; font-size: 15px; line-height: 1.7;">Hi ${escapeHtml(input.workerName)}, this payout is now marked as paid in Fixlife.</p>
    <div style="border-radius: 20px; border: 1px solid #dbe5f0; background: #ffffff; padding: 20px;">
      <div style="display: grid; gap: 14px; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));">
        <div>
          <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #2563eb;">Payout amount</div>
          <div style="margin-top: 8px; font-size: 28px; font-weight: 800; color: #0f172a;">${escapeHtml(formatMoney(input.amount))}</div>
          <div style="margin-top: 8px; font-size: 13px; color: #475569;">${escapeHtml(isBonus ? 'Bonus settlement' : 'Base worker payout')}</div>
        </div>
        <div>
          <div style="font-size: 11px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #2563eb;">Status</div>
          <div style="margin-top: 8px; font-size: 20px; font-weight: 800; color: #0f172a;">Paid</div>
          <div style="margin-top: 8px; font-size: 13px; color: #475569;">${escapeHtml(formatDateTime(input.paidAt || new Date()))}</div>
        </div>
      </div>
      <div style="margin-top: 16px; border-radius: 16px; background: #f8fafc; padding: 14px 16px; font-size: 13px; line-height: 1.7; color: #475569;">
        ${input.requestId ? `<div>Request #${escapeHtml(input.requestId)}</div>` : ''}
        ${input.serviceName ? `<div>Service: ${escapeHtml(input.serviceName)}</div>` : ''}
        ${input.cycleKey ? `<div>Cycle: ${escapeHtml(input.cycleKey)}</div>` : ''}
        ${input.bonusType ? `<div>Bonus type: ${escapeHtml(input.bonusType)}</div>` : ''}
        ${input.scheduledFor ? `<div>Scheduled for: ${escapeHtml(formatDateTime(input.scheduledFor))}</div>` : ''}
      </div>
    </div>
  `;

  const mailOptions = {
    from: `"Fixlife Billing" <${process.env.EMAIL_USER || 'no-reply@fixlife.local'}>`,
    to: input.to,
    subject: `${payoutTitle} - Fixlife`,
    html: renderEmailShell({
      eyebrow: 'Settlement',
      title: payoutTitle,
      subtitle,
      accentStart: '#1d4ed8',
      accentEnd: '#0f172a',
      bodyHtml,
    }),
    text: `${payoutTitle}
Amount: ${formatMoney(input.amount)}
${input.requestId ? `Request #${input.requestId}\n` : ''}${input.serviceName ? `Service: ${input.serviceName}\n` : ''}`,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Worker payout paid email sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending worker payout paid email:', error);
    return false;
  }
};
